query ArticleTemplate($id: String!) {
  strapiArticle(id: { eq: $id }) {
    title
    content
    image {
      childImageSharp {
        fixed(width: 200, height: 125) {
          ...GatsbyImageSharpFixed
        }
      }
    }
    author {
      id
      username
    }
  }
}
